var STCM = new Map();
STCM.set("Alabama", [7,6]);
STCM.set("Alaska", [0,0]);
STCM.set("Arizona", [2,5]);
STCM.set("Arkansas", [5,5]);
STCM.set("California", [1,4]);
STCM.set("Colorado", [3,4]);
STCM.set("Connecticut", [10,3]);
STCM.set("Delaware", [9,5]);
STCM.set("DC", [10,4]);
STCM.set("Florida", [9,7]);
STCM.set("Georgia", [8,6]);
STCM.set("Hawaii", [1,7]);
STCM.set("Idaho", [2,2]);
STCM.set("Illinois", [6,2]);
STCM.set("Indiana", [6,3]);
STCM.set("Iowa", [5,3]);
STCM.set("Kansas", [4,5]);
STCM.set("Kentucky", [6,4]);
STCM.set("Louisiana", [5,6]);
STCM.set("Maine", [11,0]);
STCM.set("Maryland", [9,4]);
STCM.set("Massachusetts", [11,2]);
STCM.set("Michigan", [8,2]);
STCM.set("Minnesota", [5,2]);
STCM.set("Mississippi", [6,6]);
STCM.set("Missouri", [5,4]);
STCM.set("Montana", [3,2]);
STCM.set("Nebraska", [4,4]);
STCM.set("Nevada", [2,3]);
STCM.set("New Hampshire", [11,1]);
STCM.set("New Jersey", [9,3]);
STCM.set("New Mexico", [3,5]);
STCM.set("New York", [9,2]);
STCM.set("North Carolina", [7,5]);
STCM.set("North Dakota", [4,2]);
STCM.set("Ohio", [7,3]);
STCM.set("Oklahoma", [4,6]);
STCM.set("Oregon", [1,3]);
STCM.set("Pennsylvania", [8,3]);
STCM.set("Rhode Island", [10, 2]);
STCM.set("South Carolina", [8,5]);
STCM.set("South Dakota", [4,3]);
STCM.set("Tennessee", [6,5]);
STCM.set("Texas", [4,7]);
STCM.set("Utah", [2,4]);
STCM.set("Vermont", [10,1]);
STCM.set("Virginia", [8,4]);
STCM.set("Washington", [1,2]);
STCM.set("West Virginia", [7,4]);
STCM.set("Wisconsin", [7,2]);
STCM.set("Wyoming", [3,3]);